### PR TITLE
WIP: feat: add explanation for filters

### LINKED ISSUE #48: [Feature]: Add explanation for filters
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

Part of #46

### Solution Description

Provide a proper explanation about the filters used in the K8sGPT CLI.
This should be added under the [explanation](https://docs.k8sgpt.ai/explanation/) section.

### Benefits

Users will be able to understand what these filters do and how to use them. 

### Potential Drawbacks

_No response_

### Additional Information

I am working on this.

### PR DESCRIPTION
**Pull request by rakshitgondwal**
Closes #48

## 📑 Description
Changes made-
- Added explanation for `filters` under explanation.
- Removed the `index.md` file under explanation.
- Fixed one typo in `reference/cli/filters.md`

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by AnaisUrlichs** [comment]
Hi there, I just took a look, I think this is a great start. At the moment, you are explaining in great detail the filter command options, what I am looking for in this section, in addition, is how it is implemented in the source code -- just as an overview where people would be able to find it. I guess we can add more detail in the future. It might be worth asking in the main K8sGPT repo or on Slack for some of the other contributors to get involved. We could merge this PR for now and create a new issue based on my feedback to address that. What do you think?

**Comment by AnaisUrlichs** [comment]
> Oh, so are you suggesting adding information on where the filter command is implemented or a certain part is implemented in the codebase?
Yes, explaining the codebase in the explanation section vs. using the CLI is in the reference section

**Comment by AlexsJones** [comment]
Is this ready to go @rakshitgondwal ?

**Comment by rakshitgondwal** [comment]
Actually, me and Anais discussed adding more information about how to navigate through the codebase for filters above, but we just merged #69 in which we provide an explanation for integrations, now have we moved on from this idea as I don't really see this idea being implemented in that PR?
If not, then I can add this additional information in separate PRs for both.

@AlexsJones @AnaisUrlichs

**Pull request closed without merging**
