### PR TITLE
flag is anonymize not anonymise

### PR DESCRIPTION
**Pull request by jkleinlercher**
Closes # 

## 📑 Description
just fixed a typo concerning the anonymize parameter

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by AnaisUrlichs** [comment]
It's British spelling analyse vs. American spelling analyze -- we can agree on one or the other; however, I am not too fuzzed about it

**Comment by jkleinlercher** [comment]
but does the flag "anonymise" work? I am afraid the code only accepts "anonymize", refered to https://github.com/k8sgpt-ai/k8sgpt/blob/3f0aea131e1e62655a10f6a51bf6238316dd6598/cmd/analyze/analyze.go#L82

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM! 
I think `--anonymize` would be the correct flag with reference to https://github.com/k8sgpt-ai/k8sgpt/blob/3f0aea131e1e62655a10f6a51bf6238316dd6598/cmd/analyze/analyze.go#L82

**Comment by AnaisUrlichs** [comment]
Upps, sorry, I did not make the connection hahahah -- thank you for the PR

**Review by AnaisUrlichs — APPROVED** [review]

**Pull request merged**
