### PR TITLE
docs: add blog to content collection

### PR DESCRIPTION
**Pull request by TylerGillson**
## 📑 Description
Add [K8sGPT + LocalAI: Unlock Kubernetes superpowers for free!](https://itnext.io/k8sgpt-localai-unlock-kubernetes-superpowers-for-free-584790de9b65) to the content collection.

Also, add an additional newline to hopefully fix the following rendering issue:
image

### CODE REVIEW

**Comment by rakshitgondwal** [comment]
@AnaisUrlichs Shouldn't we add bullet points to the blogs too or not? just like we do for videos. I think it is better readable in that way.

**Comment by AlexsJones** [comment]
maybe you could do it in another PR @rakshitgondwal ?

**Comment by rakshitgondwal** [comment]
> maybe you could do it in another PR @rakshitgondwal ?

Sure!

**Comment by rakshitgondwal** [comment]
> @AnaisUrlichs Shouldn't we add bullet points to the blogs too or not? just like we do for videos. I think it is better readable in that way.

Didn't notice but this is already fixed by Tyler in this PR.

**Pull request merged**
